### ISSUE TITLE
Wt tesla app - cannot create link

### ISSUE THREAD

**Issue by Kvatros007** [haha150/wTesla-IOS#1]
Hi

i just bought your app for my watch. I want to use it for my Tesla. Cannot create the link. Please help

**Comment by haha150** [comment]
Hi,

Did you check https://haha150.github.io/wT/ to generate token?

After you generate the token, you save the contents to a text file, and then host the file on a webserver or any hosting service where you can download files from.

Then in the app you set the link to this file.

How far did you get?

**Comment by Kvatros007** [comment]
HiYes I did but I could not understand what to do. It was a bit too technical for me. Can you help please 🙏🏼 Den 23. nov. 2022 kl. 21.49 skrev haha150 ***@***.***>:﻿
Hi,
Did you check https://haha150.github.io/wT/ to generate token?

**Comment by haha150** [comment]
Ok, so where are you stuck?

**Comment by Kvatros007** [comment]
I dont understand what to do. How to create the token link for the app. Den 24. nov. 2022 kl. 09.11 skrev haha150 ***@***.***>:﻿
Ok, so where are you stuck?

**Comment by haha150** [comment]
There are multiple ways to do this depends on your ambition level.Easy way is to download the ”auth app for tesla” on app store for IOS and generate your token there first and then save it as text file and structure as mentioned in my support page.Another way is to do it programatically, i have a repo called ”tesla-api-server”. Clone it and run ”gen.py”, this will give you a link you open and log in then follow steps from the guide in my support page.Last way is to do every request manually.Sent from my iPhoneOn 24 Nov 2022, at 12:10, Kvatros007 ***@***.***> wrote:﻿
I dont understand what to do. How to create the token link for the app. Den 24. nov. 2022 kl. 09.11 skrev haha150 ***@***.***>:﻿
Ok, so where are you stuck?
