### ISSUE TITLE
Generating token

### ISSUE THREAD

**Issue by Dazcon5** [haha150/wTesla-IOS#2]
Mate,  the details around generating the token are heavy,  any chance you can create a short video walk-through?   Cheers  - d

**Comment by haha150** [comment]
Hi,

The easiest way to generate your token, specifically refresh token is to download this app: https://apps.apple.com/us/app/auth-app-for-tesla/id1552058613

In the app login to your Tesla account and you will receive your token.

**Comment by Dazcon5** [comment]
OK thanks, I have the token ID,   I have tried to upload it into the watch app via iCloud Share,  Onedrive share and Dropbox,  entering the long URL's each time carefully and giving full access to those links for the user to download files the App returns an **Invalid Auth IP address incorrect**   Message,     I note the input does not allow copy and paste from the phone : so entering is cumbersome, but I was careful.   when entering the URL do I need to enter HTTPS:// at the font ?    Cheers - D

**Comment by haha150** [comment]
Hi,

What does the URL look like? Also if you manually visit the URL in your browser, does it show the file? (dont paste your URL or token here, its sensitive, show me a "example" of your URL)

For example i have this in my repo https://raw.githubusercontent.com/haha150/wT-IOS/main/token.txt, does your file look like this (with brackets and this JSON syntax)? You mainly need refresh token, the rest you can leave empty with double quote ("")

The app will default to HTTPS:// unless you explicitly set http:// or something else.
